language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required
services:
 - docker
script:
 - dotnet build
 - (cd ./Dockerize.NET.Tests && dotnet test)
 - dotnet pack -c Release --version-suffix $(printf %05d $TRAVIS_BUILD_NUMBER)
 - dotnet nuget push ./bin/Release/Brthor.Dockerize.NET.*.nupkg -s https://www.myget.org/F/thor/api/v2/package -k $MYGET_KEY