language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
script:
 - dotnet build
 - dotnet pack -c Release --version-suffix $(printf %05d $TRAVIS_BUILD_NUMBER)
 - dotnet nuget push ./bin/Release/Dockerize.NET.*.nupkg -s https://www.myget.org/F/thor/api/v2/package -k $MYGET_KEY